[package]
name = "token_filtering"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
solana-program = "3.0.0"
tokio = { version = "1.49.0", features = ["full"] }
